//
// Author: Mino
// Github: https://github.com/minoxs
//
#ifndef HUFFMAN_ERRORCODES_H
#define HUFFMAN_ERRORCODES_H

#define NULL_TABLE_ERROR 1
#define NULL_TREE_ERROR  2
#define WRONG_NUMBER_OF_ARGUMENTS_ERROR 3
#define FAILED_TO_READ_FILE_ERROR 4
#define FAILED_TO_WRITE_FILE_ERROR 5
#define FAILED_TO_PARSE_ARGS 6

#endif //HUFFMAN_ERRORCODES_H
